# Generated by Django 4.0.6 on 2022-07-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.IntegerField(max_length=12)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=8)),
                ('repassword', models.CharField(max_length=8)),
            ],
        ),
    ]
