# Generated by Django 4.0.6 on 2022-07-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_usertable_repassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='address',
            field=models.CharField(max_length=12),
        ),
    ]
